version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./deploy/nging:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
