# Generated by Django 2.2 on 2019-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('short_id', models.SlugField(max_length=8, primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=255)),
            ],
        ),
    ]
