# Generated by Django 2.2 on 2019-04-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='short_id',
            new_name='short_url',
        ),
    ]
