# Generated by Django 2.2 on 2019-04-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20190414_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='short_url',
            new_name='short_id',
        ),
    ]
